#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'sherlockAndAnagrams' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def sherlockAndAnagrams(s):
    # Freq Dict
    freq_dict = {}
    # First loop selects starting index 
    for s_index, s_char in enumerate(s):
        #Second loop selects ending index:
        for e_index, e_char in enumerate(s):
            if s[s_index, e_index] in freq_dict:
                freq_dict[]
            
            
            
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = sherlockAndAnagrams(s)

        fptr.write(str(result) + '\n')

    fptr.close()
