#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'sherlockAndAnagrams' function below.
#
# The function is expected to return an INTEGER.
# The function accepts STRING s as parameter.
#

def sherlockAndAnagrams(s):
    # Freq Dict
    freq_dict = {}
    # First loop selects starting index 
    for s_index, s_char in enumerate(s):
        #Second loop selects ending index:
        for e_index, e_char in enumerate(s[s_index:]):
            if(s_index >= e_index):
                continue
            print(s)
            print(s[s_index:])
            print("s_index: ", s_index)
            print("e_index: ", e_index)
            print(s[s_index:e_index])
            #create a freq table out of the sorted string
            freq_table = ''.join(sorted(s[s_index:e_index]))
            if freq_table in freq_dict:
                freq_dict[freq_table] = freq_dict[freq_table] + 1
            else:
                freq_dict[freq_table] = 0
    total = sum(freq_dict.values())
    return total
            
            
            
            

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    q = int(input().strip())

    for q_itr in range(q):
        s = input()

        result = sherlockAndAnagrams(s)

        fptr.write(str(result) + '\n')

    fptr.close()
